# Generated by Django 4.1.4 on 2022-12-10 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='televisores',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
