# Generated by Django 4.1.4 on 2022-12-11 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_televisores_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='televisores',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
